### ISSUE TITLE
Suggestion: GregTech Compability

### ISSUE THREAD

**Issue by Blocky106** [NovaEngineering-Source/ModularMachinery-Community-Edition#50]
to make modular machinery hatches work with gtce

**Comment by KasumiNova** [comment]
Most of the features have been implemented in R50.

- ME Input / Output is only compatible with inputs, outputs are not yet supported.
- The preview does not work correctly due to the special rendering of GTCE, and there is nothing I can do about it unless the GTCE developers help.
- Only GTCEu is supported, and compatibility with GTCE will probably not be proposed anytime soon, as it would require more work.

**Comment by KasumiNova** [comment]
In addition, due to the async mode of operation of MMCE, there is a performance loss when there is a GT-related Input / Output hatch in the structure (Sync mode must be used).
